export const ACTIVE_NAVAR_LINK = 'ACTIVE_NAVAR_LINK'

export const USER_LOGIN = 'USER_LOGIN'

export const SET_NOMBRE = 'SET_NOMBRE'

export const SET_PRECIOMAYOR = 'SET_PRECIOMAYOR'

export const SET_PRECIOMENOR = 'SET_PRECIOMENOR'

export const SET_TIPO = 'SET_TIPO'

export const SET_UBICACION = 'SET_UBICACION'

export const SET_HABITACIONES = 'SET_HABITACIONES'

export const SET_BAÑOS = 'SET_BAÑOS'

export const SET_M2TOTALESMAYOR = 'SET_M2TOTALESMAYOR'

export const SET_M2TOTALESMENOR = 'SET_M2TOTALESMENOR'
