/* GLOBAL STATE */

export const ACTIVE_NAVAR_LINK = 'ACTIVE_NAVAR_LINK'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const SET_NOMBRE = 'SET_NOMBRE'
export const SET_PRECIOMAYOR = 'SET_PRECIOMAYOR'
export const SET_PRECIOMENOR = 'SET_PRECIOMENOR'
export const SET_TIPO = 'SET_TIPO'
export const SET_UBICACION = 'SET_UBICACION'
export const SET_HABITACIONES = 'SET_HABITACIONES'
export const SET_BAÑOS = 'SET_BAÑOS'
export const SET_M2TOTALESMAYOR = 'SET_M2TOTALESMAYOR'
export const SET_M2TOTALESMENOR = 'SET_M2TOTALESMENOR'

/* PROPIEDADES STATE */

export const  MERGE_PROPIEDAD_IMAGEN = 'MERGE_PROPIEDAD_IMAGEN'
export const  UPDATE_PROPIEDADES = 'UPDATE_PROPIEDADES'
export const  PROPIEDAD_SELECCIONADA = 'PROPIEDAD_SELECCIONADA'
export const  ADD_PROPIEDAD = 'ADD_PROPIEDAD'
export const  DELETE_PROPIEDAD = 'DELETE_PROPIEDAD'
export const  SET_IMAGE = 'SET_IMAGE'
export const  API_CALL = 'API_CALL'
export const  GET_IMAGEN = 'GET_IMAGEN'
export const  GET_PROPIEDAD_NOMBRE = 'GET_PROPIEDAD_NOMBRE'
export const  GET_PROPIEDAD_TIPO = 'GET_PROPIEDAD_TIPO'
export const  GET_PROPIEDAD_PRECIO = 'GET_PROPIEDAD_PRECIO'
export const  GET_PROPIEDAD_UBICACION = 'GET_PROPIEDAD_UBICACION'

/* CLIENTES STATE */
export const  ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE'
export const  CLIENTES_SELECCIONADOS = 'CLIENTES_SELECCIONADOS'